name: Nightly update and publish
on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  update-and-publish:
    name: "Update and publish"
    runs-on: ubuntu-slim
    env:
      EVENT_NAME: ${{ github.event_name }}
      GIT_AUTHOR_NAME: "github-actions[bot]"
      GIT_AUTHOR_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
      GIT_COMMITTER_NAME: "github-actions[bot]"
      GIT_COMMITTER_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      
      - name: Run script
        run: |
          nix run .#update-and-publish